import os

# IMAGE PARAMETERS FOR BOTH PICAM AND USB CAM
CAPTURE_WIDTH = 320
CAPTURE_HEIGHT = 240
SKIP_FRAMES = 3
CENTER_X = CAPTURE_WIDTH // 2

# Camera status logging cadence (seconds)
PICAM_STATUS_INTERVAL_S = 5.0
PICAM_ERROR_LOG_INTERVAL_S = 3.0

# Initialization robustness
INIT_CAMERA_WARMUP_S = 2.0
INIT_SENSOR_TIMEOUT_S = 3.0

# Sensor validity thresholds
ULTRASONIC_INVALID_READING = 999
SAFETY_MIN_VALID_CM = 5
SAFETY_MAX_VALID_CM = 400

# Models
NCNN_MODEL = "/home/pi/yolo_project/orange_ball_ncnn_model"
PT_MODEL = "/home/pi/yolo_project/orange_ball.pt"
MODEL_PATH = NCNN_MODEL if os.path.exists(NCNN_MODEL) else PT_MODEL

# Navigation & Obstacle Avoidance
STOP_DIST = 40       # cm
SIDE_DIST = 35       # cm
CENTER_TOLERANCE = 32 # pixels

# Emergency / operator controls
START_STOP_KEY = 'y'

# Ball parameters
BALL_DIAMETER_CM = 4.0
BALL_PICK_DISTANCE = 30.0
BALL_PICK_LOSS_MARGIN_CM = 7

# Step-4 capture maneuver (time-based as per plan)
SLOW_FORWARD_PICK_MOTION_S = 2.0
MAX_OPEN_CLOSE_TIMES = 3
CAPTURE_FORWARD_SPEED = '2'
CAPTURE_BACKUP_SPEED = '1'
CAPTURE_BACKUP_DURATION_S = 0.22

# Approach / target lock behavior
TARGET_LOSS_GRACE_S = 1
TARGET_REACQUIRE_TURN_SPEED = '1'
TARGET_REACQUIRE_TURN_BURST_S = 0.02
TARGET_REACQUIRE_SETTLE_S = 0.10
TARGET_REACQUIRE_MAX_S = 2.0
TARGET_MATCH_MAX_DIST_PX = 110.0
TARGET_SWITCH_AREA_GAIN = 2.2

# Arm-down wall safety via PiCamera AprilTag pose (cm)
SAFE_WALL_DISTANCE = 35.0

# Mission Timing (seconds)
STEP2_CONFIRM_HOME_TIMEOUT_S = 10.0
STEP3_READY_TO_EXPLORE_S = 10.0
STEP4_SEARCH_AND_APPROACH_TIMEOUT_S = 110.0
STEP5_RETURN_HOME_TIMEOUT_S = 50.0

# Step 5 behavior (localize -> rotate -> coarse forward step)
COURSE_FWD_MOTION_DIST_CM = 30.0
COURSE_SPEED_CM_S = 10.6
COURSE_FORWARD_SPEED = '2'
STEP5_HEADING_TOL_DEG = 12.0
STEP5_COARSE_TURN_THRESHOLD_DEG = 45.0
STEP5_COARSE_TURN_BURST_S = 0.30
STEP5_FINE_TURN_BURST_S = 0.14
STEP5_FORWARD_AFTER_TURN_MAX_ERROR_DEG = 95.0
STEP5_POSE_CONFIRM_FRAMES = 2
STEP5_POSE_CONFIRM_INTERVAL_S = 0.10
STEP5_POSE_CONFIRM_MAX_POS_JUMP_M = 0.50
STEP5_POSE_CONFIRM_MAX_HEADING_JUMP_DEG = 40.0
STEP5_LOCALIZE_IMAGE_INTERVAL_S = 3.0
HOME_WALL_STOP_DISTANCE = 40.0
HOME_WALL_STOP_CONFIRM_COUNT = 2
FINE_TUNING_HOME_DIST_CM = 50.0
STEP5_RELOCALIZE_BACKUP_SPEED = '1'
STEP5_RELOCALIZE_BACKUP_DURATION_S = 1.0
STEP5_RELOCALIZE_BACKUP_SETTLE_S = 0.12

# Step 2 behavior
STEP2_BACKUP_SPEED = '1'
STEP2_BACKUP_DURATION_S = 0.35
STEP2_BACKUP_SETTLE_S = 0.45

# Step 3 behavior (user-adjustable turn to face away from home wall)
STEP3_TURN_DIR = 'R'
STEP3_TURN_SPEED = '2'
STEP3_TURN_DURATION_S = 1.15
STEP3_POST_TURN_SETTLE_S = 0.4

# Step 4 behavior
BALL_SEARCH_WINDOW_S = 16.0
BALL_APPROACH_WINDOW_S = 25.0
STEP4_BALL_CONFIRM_FRAMES = 2
STEP4_BALL_CONFIRM_MAX_X_JUMP_PX = 45.0
STEP4_BALL_CONFIRM_MAX_DIST_JUMP_CM = 20.0


# Generic move timings
OBSTACLE_BACKUP_SPEED = '1'
OBSTACLE_BACKUP_DURATION_S = 0.25
OBSTACLE_TURN_DIR = 'L'
OBSTACLE_TURN_SPEED = '1'
OBSTACLE_TURN_DURATION_S = 0.28
OBSTACLE_SETTLE_S = 0.15
OBSTACLE_SIDE_CHECK_ENABLED = True

SEARCH_TURN_DIR = 'R'
SEARCH_TURN_SPEED = '1'
SEARCH_TURN_DURATION_S = 0.10
SEARCH_TURN_SETTLE_S = 0.20

APPROACH_FORWARD_SPEED = '1'
APPROACH_FORWARD_BURST_S = 0.12
APPROACH_FORWARD_SETTLE_S = 0.08
APPROACH_TRIM_TOLERANCE_PX = 12
APPROACH_TRIM_TURN_BURST_S = 0.03


CENTERING_TURN_SPEED = '1'
CENTERING_TURN_BURST_S = 0.05
CENTERING_SETTLE_S = 0.14

# Specify Home Tags
HOME_TAG_IDS = [14, 15]
